```{r setup, include=FALSE}
library(pegas)
library(knitr)
library(ape)
library(tidyverse)
library(RColorBrewer)
library(igraph)

setwd("/Users/henrysun_1/Desktop/Duke/PhD 2025-2026/callinectes_co1") 
getwd()
```


```{r}
# dna <- read.nexus.data("/Users/henrysun_1/Desktop/Duke/PhD 2025-2026/callinectes_co1/processed/combined_unique_trimmed.nexus")

dna <- read.dna("/Users/henrysun_1/Desktop/Duke/PhD 2025-2026/callinectes_co1/processed/combined_unique_trimmed.fasta", format="fasta")

traits <- read.csv("/Users/henrysun_1/Desktop/Duke/PhD 2025-2026/callinectes_co1/processed/misc/population_traits.csv")

```

## Initial plotting with guidance from Github pages doc

```{r}

hap <- haplotype(dna)
hapInfo <- stack(setNames(attr(hap,"index"),rownames(hap)))
names(hapInfo) <- c("index","haplotype")

hapInfo$index
merged <- data.frame(cbind(hapInfo,traits[hapInfo$index,]))
pie <- table(merged$haplotype,merged$Population)

net <- haploNet(hap)


```

```{r}
freq <- attr(net, "freq")
freq_scaled <- (log(freq + 1) / log(max(freq) + 1))
size_scaled <- 1 + 20 * freq_scaled

n_pop <- ncol(freq)
cols <- brewer.pal(min(n_pop, 8), "Set3")

par(mar = c(3, 3, 3, 3))

plot(
  net,
  size = size_scaled,
  bg = cols,
  pie = pie,
  show.mutation = 0,
  scale.ratio = 30,
  asp = 1,
  labels = FALSE,
  fast = TRUE
)

legend(
  "topleft",
  legend = colnames(pie),
  col = cols,
  pch = 15,
  ncol = 1,
  pt.cex = 1.5,
  bty="n"
)

```
```{r warning = FALSE}
setwd("/Users/henrysun_1/Desktop/Duke/PhD 2025-2026/callinectes_co1")
write.csv(merged, "processed/traits.csv")
```


